# GitHub Actions Workflow Template
#
# This file is a TEMPLATE for automated screenshot generation.
# To use it, copy this file to openadapt-viewer repository:
#
#   cp github-workflows-template.yml \
#      /Users/abrichr/oa/src/openadapt-viewer/.github/workflows/update-web-screenshots.yml
#
# Then configure secrets in GitHub:
#   Settings → Secrets and variables → Actions → New repository secret
#   Name: WEB_REPO_TOKEN
#   Value: Personal access token with repo permissions

name: Update Landing Page Screenshots

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      skip_pr:
        description: 'Skip PR creation and commit directly to branch'
        required: false
        default: 'false'

  # Weekly on Sunday at midnight UTC
  schedule:
    - cron: '0 0 * * 0'

  # When viewer files change
  push:
    paths:
      - 'segmentation_viewer.html'
      - 'benchmark_viewer.html'
      - 'synthetic_demo_viewer.html'
      - 'scripts/generate_comprehensive_screenshots.py'
      - 'scripts/generate_segmentation_screenshots.py'
      - 'test_episodes.json'
    branches:
      - main

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout openadapt-viewer
        uses: actions/checkout@v4
        with:
          repository: OpenAdaptAI/openadapt-viewer
          path: openadapt-viewer

      - name: Checkout openadapt-web
        uses: actions/checkout@v4
        with:
          repository: OpenAdaptAI/openadapt-web
          path: openadapt-web
          token: ${{ secrets.WEB_REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cd openadapt-viewer
          uv sync
          uv pip install playwright
          uv run playwright install chromium --with-deps

      - name: Check dependencies
        run: |
          cd openadapt-viewer
          uv run python scripts/generate_comprehensive_screenshots.py --check-deps

      - name: Generate screenshots
        run: |
          cd openadapt-viewer
          mkdir -p /tmp/oa-screenshots

          # Capture viewer screenshots (if HTML files exist)
          if [ -f "temp/turn-off-nightshift_viewer.html" ] || [ -f "temp/demo_new_viewer.html" ]; then
            echo "Generating capture viewer screenshots..."
            uv run python scripts/generate_comprehensive_screenshots.py \
              --viewers capture \
              --output /tmp/oa-screenshots/capture || true
          fi

          # Segmentation viewer screenshots
          if [ -f "segmentation_viewer.html" ] && [ -f "test_episodes.json" ]; then
            echo "Generating segmentation viewer screenshots..."
            uv run python scripts/generate_segmentation_screenshots.py \
              --skip-responsive \
              --output /tmp/oa-screenshots/segmentation
          fi

          # Benchmark viewer screenshots (when implemented)
          # if [ -f "benchmark_viewer.html" ]; then
          #   echo "Generating benchmark viewer screenshots..."
          #   # Add benchmark generation command here
          # fi

      - name: Copy screenshots to openadapt-web
        run: |
          WEB_DIR=openadapt-web/public/images/screenshots
          mkdir -p $WEB_DIR

          # Copy all generated screenshots
          if [ -d "/tmp/oa-screenshots" ]; then
            cp -r /tmp/oa-screenshots/* $WEB_DIR/
          fi

          # Generate metadata
          cat > $WEB_DIR/README.md <<EOF
          # Autogenerated Screenshots

          These screenshots are automatically generated from openadapt-viewer.

          **DO NOT EDIT MANUALLY** - Changes will be overwritten.

          ## Generation Info

          - **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - **Workflow**: ${{ github.workflow }}
          - **Run ID**: ${{ github.run_id }}
          - **Triggered by**: ${{ github.event_name }}
          - **Commit**: ${{ github.sha }}
          - **Branch**: ${{ github.ref_name }}

          ## Screenshots

          EOF

          # List screenshots
          for viewer_dir in $WEB_DIR/*; do
            if [ -d "$viewer_dir" ]; then
              viewer_name=$(basename "$viewer_dir")
              echo "### $viewer_name" >> $WEB_DIR/README.md
              echo "" >> $WEB_DIR/README.md
              find "$viewer_dir" -name "*.png" -exec basename {} \; | sort | while read file; do
                size=$(du -h "$viewer_dir/$file" | cut -f1)
                echo "- $file ($size)" >> $WEB_DIR/README.md
              done
              echo "" >> $WEB_DIR/README.md
            fi
          done

      - name: Check if screenshots changed
        id: check_changes
        run: |
          cd openadapt-web
          if git diff --quiet public/images/screenshots/; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in screenshots"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in screenshots"
          fi

      - name: List generated screenshots
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd openadapt-web
          echo "Changed files:"
          git diff --name-only public/images/screenshots/
          echo ""
          echo "Screenshot sizes:"
          find public/images/screenshots -name "*.png" -exec du -h {} \; | sort -k2

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true' && github.event.inputs.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          path: openadapt-web
          token: ${{ secrets.WEB_REPO_TOKEN }}
          commit-message: |
            Update autogenerated screenshots from openadapt-viewer

            Generated from openadapt-viewer commit ${{ github.sha }}
            Workflow run: ${{ github.run_id }}
          branch: autoupdate-screenshots-${{ github.run_id }}
          delete-branch: true
          title: "Update autogenerated screenshots"
          body: |
            ## Summary

            Automated update of landing page screenshots from openadapt-viewer.

            ## Details

            - **Source Repo**: openadapt-viewer
            - **Source Commit**: ${{ github.sha }}
            - **Triggered by**: ${{ github.event_name }}
            - **Workflow Run**: ${{ github.run_id }}
            - **Generated**: ${{ github.run_started_at }}

            ## Changes

            Screenshots have been regenerated for the following viewers:
            - Capture Viewer (if available)
            - Segmentation Viewer
            - Benchmark Viewer (if available)

            ## Testing

            - [ ] Verify screenshots load correctly in Vercel preview
            - [ ] Check image quality and sizes
            - [ ] Test responsive design
            - [ ] Verify no console errors

            ## Action Required

            Please review the screenshots and merge if they look good.

            ---

            *This PR was automatically generated by the `update-web-screenshots` workflow.*
          labels: |
            automated
            screenshots
          assignees: abrichr

      - name: Summary
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd openadapt-web
          echo "## Screenshot Generation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status**: ✓ Screenshots generated successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Generated Files" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          find public/images/screenshots -name "*.png" -exec du -h {} \; | sort -k2 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          TOTAL_SIZE=$(du -sh public/images/screenshots | cut -f1)
          TOTAL_COUNT=$(find public/images/screenshots -name "*.png" | wc -l)

          echo "**Total**: $TOTAL_COUNT screenshots ($TOTAL_SIZE)" >> $GITHUB_STEP_SUMMARY

          if [ "${{ github.event.inputs.skip_pr }}" = "true" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Note**: PR creation was skipped (manual input)" >> $GITHUB_STEP_SUMMARY
          fi

      - name: No changes detected
        if: steps.check_changes.outputs.changed == 'false'
        run: |
          echo "## Screenshot Generation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status**: ℹ️ No changes detected" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Screenshots were regenerated but no differences were found." >> $GITHUB_STEP_SUMMARY
          echo "No PR will be created." >> $GITHUB_STEP_SUMMARY
